### ISSUE TITLE
Code signing for Windows SACRO app installer

### ISSUE THREAD

**Issue by bloodearnest** [opensafely-core/SACRO-Viewer#14]
Signing windows binaries is fairly horrid.

We need to: 

a) buy an EV cert from a dodgy provide ($300+/year)
b) set up a Azure key vault to hold the key ($60/year)
c) configure the vault with the above key
d) add signing step to CI 

Example here: https://melatonin.dev/blog/how-to-code-sign-windows-installers-with-an-ev-cert-on-github-actions/

Requires #13

**Comment by lucyb** [comment]
Note: this may not be necessary if we're only installing on a low number of machines. We should wait for feedback until we make a decision on this
