### ISSUE TITLE
Integrate new format for per-cell ACRO results

### ISSUE THREAD

**Issue by benbc** [opensafely-core/SACRO-Viewer#145]
ACRO v0.3.0 adds a new coordinate (rather than mask-based) format for per-cell results. (See https://github.com/AI-SDC/ACRO/pull/104 and https://github.com/AI-SDC/ACRO/pull/114.)

Note that until this change, there has (in principle) been no way to combine per-cell results with multi-file outputs. We have some [special-case code](https://github.com/opensafely-core/sacro/blob/780ba99ff9246b2927ae1c456da8370b4ccde129/assets/src/scripts/_output-click.js#L201-L202) to accommodate this which will need to be changed.

The old format is still present as well, so we don't need to integrate the new format in order to take the release (note this is a correction to Tom's comment below). However it's possible that the old format will be removed at some point, so we should start using the new format instead.

**Comment by madwort** [comment]
we don't need to integrate this right now, but we will need to integrate next time we update from upstream.

**Comment by bloodearnest** [comment]
https://github.com/opensafely-core/sacro/pull/225

This parses the slightly awkward data structure in ACRO to a simpler to use one in the UI JSON.

Still needs the UI part, the cell highlighting code needs to index into the new "cell_index" object with `${x}{y}` table coords.

**Comment by lucyb** [comment]
Is this still being worked on or has it been put to one side now?

**Comment by lucyb** [comment]
@bloodearnest I know you were working on this. Did you get any further?

**Comment by bloodearnest** [comment]
No, I've been sidetracked with tech support

**Comment by bloodearnest** [comment]
This is done now with #251
