### ISSUE TITLE
If you click on approve/reject promptly after filling in the required comment the click is ignored

### ISSUE THREAD

**Issue by benbc** [opensafely-core/SACRO-Viewer#207]
After you fill in the comment for an individual file, there is a noticeable period during which the accept/reject buttons don't respond to clicks. The styling of the previously-disabled button changes immediately, but if you click on it straight away nothing happens. The other button which was previously clickable becomes briefly unclickable (although its styling doesn't change). After a moment or two both buttons behave as expected.

I've also noticed that if you click on it when it's in this state (visually enabled, but unclickable), then switch away to another file, then switch back to the previous one; then the button appears disabled, even though there is a comment.

**Comment by tomodwyer** [comment]
Currently blocked as I cannot replicate it in my Windows environment. I will be sending out instructions on how to set up debugging in production installs for others to test.

**Comment by tomodwyer** [comment]
@benbc this is currently in blocked, do we want to remove it from the project board until we can get users to test it?
