### ISSUE TITLE
Switch to using new per-cell annotation format

### ISSUE THREAD

**Issue by benbc** [opensafely-core/SACRO-Viewer#247]
The ACRO library produces per-cell annotations in two formats. The old one, which we use, and a new, more efficient one.

We didn't adopt the new format when it was introduced, but we'd like to do that now as a bit of clean-up before we hand over ownership of the repo to UWE.

**Comment by bloodearnest** [comment]
So, the python side of this was already done previously, it seems.

Have discussed with Tom O and he will update the js side.
