### ISSUE TITLE
PyOxidizer not bundling staticfiles

### ISSUE THREAD

**Issue by tomodwyer** [opensafely-core/SACRO-Viewer#32]
Test with [f994ab3](https://github.com/opensafely-core/sacro/pull/31/commits/f994ab3a99f27ff10dbdddfa0eb7ffa19e6bc8c3).

## Steps to replicate

1. `just devenv`
2. `just build`
3. `npm run electron-dev`

### Error code

```
Cannot read Vite manifest file at /Users/[...]/sacro/build/aarch64-apple-darwin/release/install/sacro/lib/staticfiles/manifest.json : [Errno 2] No such file or directory: '/Users/[...]/sacro/build/aarch64-apple-darwin/release/install/sacro/lib/staticfiles/manifest.json'
```

## Screenshots

![CleanShot 2023-05-31 at 10 43 28@2x](https://github.com/opensafely-core/sacro/assets/24863179/a790e263-130b-43fd-9f21-c33b577cfa45)

## Workaround

Add to the `extraResources` in `package.json`:

```json
{
  "from": "staticfiles",
  "to": "sacro/lib/staticfiles",
  "filter": [
    "**/*"
  ]
}
```

This will add the files in the correct location for a built Electron app, but not the dev process.

**Comment by bloodearnest** [comment]
Fixed a long time ago
