### ISSUE TITLE
Output-checker feedback on ACRO for UWE

### ISSUE THREAD

**Issue by benbc** [opensafely-core/SACRO-Viewer#52]
We'd like to get feedback on ACRO as it exists today from a BI output checker, please, which we can pass to the UWE team who developed it.

**Comment by HelenCEBM** [comment]
Please could you post a link to instructions/downloads? Can you summarise what kind of feedback you are looking for?

**Comment by bloodearnest** [comment]
Blocked on big refactor landing in ACRO

**Comment by benbc** [comment]
I'm removing this from the Pipeline team project and will track it myself.
