### ISSUE TITLE
Use custom ACRO json file extension and associate it in windows with the ACRO viewer app

### ISSUE THREAD

**Issue by bloodearnest** [opensafely-core/SACRO-Viewer#63]
e.g. get ACRO to generate `results.acro`, and associate .acro file with app.

This means users can just double click the .acro file (which will have the apps icon) to launch it with the chosen directory/outputs

This is better UX that getting users to choose the file/directory via the open file dialog

**Comment by lucyb** [comment]
Need to speak to the UWE team about this idea before starting work. BBC is sending the message over to them
