### ISSUE TITLE
Manual release process

### ISSUE THREAD

**Issue by bloodearnest** [opensafely-core/SACRO-Viewer#90]
We have an artifact uploaded in CI for very commit to main.

We want to take that artifact and make it to a release via a manual process.

We should be able to do this using via a manually triggerd action, something like

1. wget https://nightly.link/opensafely-core/sacro/workflows/main/main/SACRO-latest-windows-build.zip
2. unzip SACRO-latest-windows-build.zip
3. gh release create --draft --generate-notes $VERSION SACRO*.msi
4. Go to github release UI and edit release notes if needed
5. Make it non-draft (i.e. publish)

We need to figure out how to bump the version in the metadata, we may want to trigger this on tag push, perhaps.

**Comment by lucyb** [comment]
I'm going to remove this from the board until we get an indication from Ben about when we'll need to do this.
